---
version: 2
updates:
  - package-ecosystem: pip
    directory: /.config/
    schedule:
      interval: monthly
    labels:
      - "dependencies"
      - "skip-changelog"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "skip-changelog"
