---
proseWrap: always
jsonRecursiveSort: true
tabWidth: 2
useTabs: false
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      # compatibility with yamllint
      proseWrap: preserve
