site_name: 42picky
site_url: https://42picky.readthedocs.io/
repo_url: https://github.com/42picky/42picky.github.io

theme:
  name: "material"
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - content.code.copy
    - content.action.edit
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: amber
      accent: "deep orange"
      scheme: default
      logos: assets/images/logo.svg
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: "deep orange"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ansible/devtools
# nav:
#   - home: index.md

plugins:
  - search
  - social
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: facelessuser
      repo: pymdown-extensions
      normalize_issue_symbols: true
  - markdown_include.include:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
